CREATE TABLE JOB20230607_1 (
EMPNO NUMBER(4),
ENAME VARCHAR2(10),
JOB VARCHAR2(10),
DEPTNO NUMBER(2)
);
 
INSERT INTO JOB20230607_1 (EMPNO, ENAME, JOB, DEPTNO)
VALUES(001, '한여진', '경찰', 24);
 
INSERT INTO JOB20230607_1 (EMPNO, ENAME, JOB, DEPTNO)
VALUES(002, '황시목', '검사', 37);
 
INSERT INTO JOB20230607_1 (EMPNO, ENAME, JOB, DEPTNO)
VALUES(003, '강원철', '검사', 50);
 
INSERT INTO JOB20230607_1 (EMPNO, ENAME, JOB, DEPTNO)
VALUES(004, '장건', '경찰', 22);
 
INSERT INTO JOB20230607_1 (EMPNO, ENAME, JOB, DEPTNO)
VALUES(005, '이연재', 'CEO', 80);
 
SELECT * FROM JOB20230607_1;

DECLARE
   CURSOR CUR_JOB IS SELECT * FROM JOB20230607_1; -- 커서 선언
   V_JOB JOB20230607_1%ROWTYPE; --변수 선언, 모든 열의 데이터를 갖고 옴(행참조 : %ROWTYPE)
BEGIN
    OPEN CUR_JOB; --커서 열기
    LOOP --반복
    FETCH CUR_JOB INTO V_JOB; --CUR_JOB의 한 행을 V_JOB에 넣음
    IF CUR_JOB%NOTFOUND THEN
    EXIT;
    END IF; --조건문을 통해 루프 탈출
    DBMS_OUTPUT.PUT_LINE('EMPNO :' || V_JOB.EMPNO ||
                         'ENAME :' || V_JOB.ENAME ||
                         'JOB :' || V_JOB.JOB ||
                         'DEPTNO :' || V_JOB.DEPTNO);
    END LOOP;
    CLOSE CUR_JOB;
END;

SELECT * FROM JOB20230607_1;


CREATE OR REPLACE PROCEDURE VALIDATE_JOB
(
    V_EMPNO JOB20230607_1.EMPNO%TYPE,
    V_DEPTNO JOB20230607_1.DEPTNO%TYPE
)
AS
    V_JOB JOB20230607_1%ROWTYPE;
    CURSOR CUR_JOB IS SELECT * FROM JOB20230607_1 WHERE EMPNO = V_EMPNO;
BEGIN
    OPEN CUR_JOB;
    FETCH CUR_JOB INTO V_JOB;
    IF CUR_JOB%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE('회원번호 불일치');
    ELSIF V_DEPTNO <> V_JOB.DEPTNO THEN
        DBMS_OUTPUT.PUT_LINE('부서번호 불일치');
    ELSE
        DBMS_OUTPUT.PUT_LINE('인증 성공');
    END IF;
CLOSE CUR_JOB;
END;
 
EXECUTE VALIDATE_JOB(1, 37);
EXECUTE VALIDATE_JOB(4, 22);
